# Generated by Django 3.2.5 on 2021-07-06 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Servicio')),
                ('nombre_servicio', models.CharField(max_length=50, verbose_name='Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='Rut proveedor')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(max_length=100, verbose_name='Descripcion')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servicio')),
            ],
        ),
    ]
