# Generated by Django 3.2.5 on 2021-07-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='rut',
            field=models.IntegerField(max_length=13, primary_key=True, serialize=False, verbose_name='Rut proveedor'),
        ),
    ]
