# Generated by Django 3.2.5 on 2021-07-08 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
